use_frameworks!

platform :ios, '8.0'

pod 'Orchestra', path: '../../'
pod 'Cartography'
pod 'Hue', git: 'https://github.com/hyperoslo/Hue'
pod 'Cache', git: 'https://github.com/hyperoslo/Cache'
pod 'Imaginary', git: 'https://github.com/hyperoslo/Imaginary'
